### PR TITLE
Updates to tdlib version 1.7.0

### PR DESCRIPTION
**Pull request by motylkov**
Field 'SenderUserID' in 'Message' is removed in the new version of the library tdlib and this does not make it possible to use it. I propose to gradually update. Other updates (https://github.com/tdlib/td/blob/master/CHANGELOG.md) also need to be added. Because the number of users of the new version will only increase.

### CODE REVIEW

**Comment by Arman92** [comment]
These files are auto generated, can you please try updating the methods.go and types.go with [this library](https://github.com/Arman92/go-tl-parser)?

**Comment by motylkov** [comment]
And I thought they looked so strange...

**Comment by motylkov** [comment]
Okay. I did it. Should I close this pull request and send a new one? Or just send a new commit?

**Comment by Arman92** [comment]
Thank you @motylkov

@all-contributors please add @motylkov for upgrading the tdlib codes

**Pull request merged**
